version: "3"
services:
        yilang-server:
                container_name: yilang-server
                image: latest/yilang-server
                restart: always
                build: .
                ports:
                        - "5875:3000"
                links:
                        - mongo
                depends_on:
                        - mongo
        mongo:
                container_name: mongo
                image: mongo
                volumes:
                        - ./data:/data/db
                ports:
                        - "27017:27017"
